### PR TITLE
multi service cfg

### PR DESCRIPTION
**Pull request by zerwes**
Allow configuration of multiple services aka. front/back instances.
Preparation for later to deprecate the old var's.
Based on #45

### CODE REVIEW

**Comment by corym-vermeer** [comment]
+1

This is a great enhancement to the overall role and removes an impediment to use the role to use multiple frontend/backend configurations.

**Comment by zerwes** [comment]
> +1
> 
> This is a great enhancement to the overall role and removes an impediment to use the role to use multiple frontend/backend configurations.

thx ... exactly this was my intention and my requirements. And in the spirit of open source I was thinking of improving existing stuff and not re-inventing the wheel ...
I hope it will not die like #45 due to https://www.jeffgeerling.com/blog/2020/enabling-stale-issue-bot-on-my-github-repositories

Meanwhile, if you like, you can use the rls branch of the fork
https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-role-haproxy/tree/rls
Here I try to merge all PRs I need and keep it up to date with upstream ...

**Comment by zerwes** [comment]
@corym-vermeer : if you can use the improved version successfully, you can review and comment the changes. I think this would be of some help for @geerlingguy having some ACKs from _independent_ side ...

**Comment by zerwes** [comment]
... #48 shows that there are more people requiring the option to configure multiple front-/backends ...
I have tried in my PR not to be to invasive and not to change the settings used before, but just extend them and add more options, so it will not break existing setups but offer more flexibility for new configurations, even with the option to deprecate the old syntax and issue a warning if they are in use. But that was my personal idea of a good solution.
I would not mind to join forces to get a good compromise ...

**Comment by redat00** [comment]
Adding myself in this. It would be a great addition to the role if we could have multiples frontend/backend!

**Comment by zerwes** [comment]
https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-role-haproxy/tree/main

**Pull request closed without merging**
