### PR TITLE
Add stats page option

### PR DESCRIPTION
**Pull request by Lusitaniae**
See issue #15.
Option to configure stats page for haproxy.

Disabled by default.
Hides HA Proxy version from the stats page.
Possible to set username and password.

I don't have experience running haproxy, what do you think @geerlingguy ?

### CODE REVIEW

**Comment by Lusitaniae** [comment]
Just want to point out, that initially I also tried to restrict access to stats page with:

    acl network_allowed src 127.0.0.0/8
    acl network_allowed src 10.0.0.0/8
    tcp-request connection reject if !network_allowed

but I removed since:
1) it only works with HAProxy 1.5 and forward
2) easier to manage with a firewall role

**Comment by andmos** [comment]
@geerlingguy this would be nice to get merged, I also have the same need. Thanks in advance 😃

**Comment by Lusitaniae** [comment]
still valid

**Comment by Lusitaniae** [comment]
still valid

**Comment by Lusitaniae** [comment]
still valid

**Pull request closed without merging**
