### PR TITLE
Making health check optional

### PR DESCRIPTION
**Pull request by marksteele**

### CODE REVIEW

**Comment by geerlingguy** [comment]
This looks reasonable to me. Since it's changing a default setting, it will be a minor version release, so I may wait to merge a little longer.

**Comment by wyaeld** [comment]
The haproxy healthcheck value is a bit of a cryptic string, and I think there is value in having a sensible default there.  @geerlingguy what do you think about leaving the value as it was, but adding a `haproxy_backend_httpchk_enabled` boolean that gets used in the template.  default to either on/off based on what you think is the most reasonable.

**Comment by geerlingguy** [comment]
For reference:
- https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4-option%20httpchk
- https://www.haproxy.com/doc/aloha/7.0/haproxy/healthchecks.html#checking-a-http-service

I'm all for keeping a sensible default. Maybe we leave it as-is (the string that's present now), but still allow  a value of `''`, and if that's the value (in someone's playbook overriding the default), then it won't be added?

@marksteele sound good to you?

**Comment by marksteele** [comment]
Having a default healthcheck is not sensible simply because it makes assumptions about the backend system. The very reason I submitted this patch was because the default settings broke my system.

I'd argue all values should be explicitly set with no defaults, but that's just me. (The reasoning of course, is that you expose the full range of functionality of the system being configured, instead of whatever the module writer happened to need at a point in time).

**Comment by geerlingguy** [comment]
@marksteele - I'll merge this, but I'm going to keep the default so I don't have to do a major version bump—I'd rather people have things break on initial install (since it should be tested on non-prod infra), then they set a good/working healthcheck as a result, rather than having people not realize there isn't any healthcheck in place after their proxy has been happily serving up 500/400 errors :)

**Comment by geerlingguy** [comment]
If you just set `haproxy_backend_httpchk: ''` in your vars, it will disable the healthcheck.

**Pull request merged**
