### PR TITLE
Allow extra configs and multiple back and frontends

### LINKED ISSUE #3: Multiple frontends
Is it possible to have multiple frontends?
In my case I need to have port 80 for non-ssl and 443 for ssl requests.

### LINKED ISSUE #19: add rabbitmq
Hi jeff,

I am looking at your ansible haproxy role and I have a few question.

1)	How can I add this section to the template?
listen rabbitmq
    bind *:5672
    mode tcp
    option tcplog
    balance roundrobin
    server moc-dbs-01 172.25.1.121:5672 check inter 5000 rise 2 fall 3
    server moc-dbs-02 172.25.1.159:5672 check inter 5000 rise 2 fall 3
2)	The server values  comes from the hosts file
[haproxy]
moc-dbs-03
moc-dbs-04

[rabbitmq]
moc-dbs-01
moc-dbs-02

Haproxy role is ran against hosts “haproxy” , the new section is defined by the hosts”rabbitmq”

### LINKED ISSUE #22: Additional configs for frontends and backends
Currently it's not possible to add additional configs to do things like multi-domain balancing as described [here](https://seanmcgary.com/posts/haproxy---route-by-domain-name/) because there's no way to add these extra configurations (acl, use_backend, etc) to the generated haproxy config file.

@geerlingguy If I prepared a PR enabling arbitrary extra configuration in the frontend and backends would you consider accepting it?

### PR DESCRIPTION
**Pull request by emmetog**
Fixes #22 
Fixes #3 
Fixes #19 

This PR makes the following changes:
* Allows specifying multiple frontends and backends
* Allows specifying free-form "extra configs" for each frontend and backend

### CODE REVIEW

**Comment by emmetog** [comment]
Hi @geerlingguy, do you have any thoughts on this PR? Anything I can do to help get it merged?

Thanks!

**Comment by chrisbalmer** [comment]
@geerlingguy any chance we can get this merged? It would be great to have support for multiple frontends/backends. I forked the repo to add this feature and then was pleasantly surprised to find it waiting as a PR already written by @emmetog

**Comment by geerlingguy** [comment]
This is a fairly major PR that changes a lot of code... it will take some time to review, and may also be more of an architectural shift than I would like to make (just based on a quick glance).

**Comment by emmetog** [comment]
Hi @geerlingguy. No problem. Do you think we'll be able to work on this PR to turn it into something that you'd be willing to merge or is the architectural shift too much?

**Comment by rockandska** [comment]
Hi,

Just my two cents concerning this PR, but having some specific needs too, why not just let the user define a personal template ?
Due to the many settings who could be done with HaProxy, none of the template we could imagine will cover all the needs of all the people or it will require to be a Jinja KungFu Master, hard to understand and too many variables. :smile: 
Having user defined templating at the playbook level will let the users fine tuning their configuration if the default template doesn't cover their needs by allow them to have full control on it.

Any thoughts @geerlingguy ?

Regards,

**Pull request closed without merging**
